### ISSUE TITLE
部分插件的命名注释

### ISSUE THREAD

**Issue by tuo21** [yancymin/figmaCN#48]
这里是一些自己用的插件命名注释，对一些不常用的插件提供了一些翻译，免得安装之后都忘了是干嘛的了。

```
  [`SkewDat`, `SkewDat 斜切`],
  [`SmoothShadow`, `SmoothShadow 平滑阴影`],
  [`Arrow Auto`, `Arrow Auto 自动箭头`],
  [`Autoflow`, `Autoflow 自动流程`],
  [`EasyMask`, `EasyMask 简单遮罩`],
  [`Filter`, `Filter 滤镜`],
  [`Confetti`, `Confetti 彩屑`],
  [`Get Waves`, `Get Waves 波浪线`],
  [`Hero Patterns for Figma`, `Hero Patterns for Figma 填充图形`],
  [`Please select at least one layer.`, `请选择一个页面`],
  [`LottieFiles`, `Lottie动画`],
  [`Palette`, `Palette调色盘`],
  [`Pixel Perfect`, `Pixel Perfect 完美像素`],
  [`Wireframe`, `Wireframe 线框组件`],
```

**Comment by yancymin** [comment]
> 这里是一些自己用的插件命名注释，对一些不常用的插件提供了一些翻译，免得安装之后都忘了是干嘛的了。
> 
> ```
>   [`SkewDat`, `SkewDat 斜切`],
>   [`SmoothShadow`, `SmoothShadow 平滑阴影`],
>   [`Arrow Auto`, `Arrow Auto 自动箭头`],
>   [`Autoflow`, `Autoflow 自动流程`],
>   [`EasyMask`, `EasyMask 简单遮罩`],
>   [`Filter`, `Filter 滤镜`],
>   [`Confetti`, `Confetti 彩屑`],
>   [`Get Waves`, `Get Waves 波浪线`],
>   [`Hero Patterns for Figma`, `Hero Patterns for Figma 填充图形`],
>   [`Please select at least one layer.`, `请选择一个页面`],
>   [`LottieFiles`, `Lottie动画`],
>   [`Palette`, `Palette调色盘`],
>   [`Pixel Perfect`, `Pixel Perfect 完美像素`],
>   [`Wireframe`, `Wireframe 线框组件`],
> ```

hello，暂时不考虑插件的名称汉化，可以安装 https://moonvy.com/figmaEX/ 自行备注。
